services:
  # Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:13
    # No se exponen puertos al host para mayor seguridad
    env_file:
      - ./db.env # Carga las variables de entorno para la BD
    volumes:
      - db_data:/var/lib/postgresql/data # Persiste los datos de la BD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apiuser -d dbApi"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - private_net # Conectada únicamente a la red privada

# Definición de volúmenes para la persistencia
volumes:
  db_data:
    driver: local